---
- name: Install Rabbitmq-server.service
  yum:
    name: rabbitmq-server
  notify:
    - start rabbitmq-server.service

- name: Add LimitNOFILE=infinity
  lineinfile:
    dest: "/usr/lib/systemd/system/rabbitmq-server.service"
    insertafter: 'Type=notify'
    line: "LimitNOFILE=infinity"

- name: Copy script check
  copy:
   src: count_clustered_nodes.py
   dest: "{{ deploy_directory }}/" 
   mode: '0777'

- name: Check if clustered
  command: "python3 {{ deploy_directory }}/count_clustered_nodes.py"
  check_mode: no
  failed_when: false
  register: nodes_count
  changed_when: False

- name: Set fact status rabbitmq cluster
  set_fact: 
      nodes_rabbitmq_count: "{{ nodes_count.stdout | int }}"

- include_tasks: config_rabbitmq.yml
  when: nodes_rabbitmq_count | int < groups['controller'] | length | int
