---
- name: Check /etc/neutron/neutron.conf.bak existed
  stat:
    path: /etc/neutron/neutron.conf.bak
  register: neutron_conf_bak

- name: Check /etc/neutron/plugins/ml2/ml2_conf.ini.bak  existed
  stat:
    path: /etc/neutron/plugins/ml2/ml2_conf.ini.bak
  register: ml2_conf_ini_bak

- name: Check /etc/neutron/plugins/ml2/openvswitch_agent.ini.bak existed
  stat:
    path: /etc/neutron/plugins/ml2/openvswitch_agent.ini.bak
  register: openvswitch_agent_ini_bak

- name: Check /etc/neutron/l3_agent.ini.bak existed
  stat:
    path: /etc/neutron/l3_agent.ini.bak
  register: l3_agent_ini_bak

- name: Check /etc/neutron/dhcp_agent.ini.bak existed
  stat:
    path: /etc/neutron/dhcp_agent.ini.bak
  register: dhcp_agent_ini_bak

- name: Check /etc/neutron/metadata_agent.ini.bak existed
  stat:
    path: /etc/neutron/metadata_agent.ini.bak
  register: metadata_agent_ini_bak

- name: Backup file config neutron.conf
  copy:
    src: /etc/neutron/neutron.conf
    dest: /etc/neutron/neutron.conf.bak
    remote_src: yes
  when:
    - not neutron_conf_bak.stat.exists

- name: Backup file config ml2_conf.ini
  copy: 
    src: /etc/neutron/plugins/ml2/ml2_conf.ini
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini.bak
    remote_src: yes
  when:
    - not ml2_conf_ini_bak.stat.exists

- name: Backup file openvswitch_agent.ini
  copy:
    src: /etc/neutron/plugins/ml2/openvswitch_agent.ini
    dest: /etc/neutron/plugins/ml2/openvswitch_agent.ini.bak
    remote_src: yes
  when:
    - not openvswitch_agent_ini_bak.stat.exists

- name: Backup file config l3_agent.ini
  copy: 
    src: /etc/neutron/l3_agent.ini
    dest: /etc/neutron/l3_agent.ini.bak
    remote_src: yes
  when:
    - not l3_agent_ini_bak.stat.exists   

- name: Backup file config dhcp_agent.ini
  copy: 
    src: /etc/neutron/dhcp_agent.ini
    dest: /etc/neutron/dhcp_agent.ini.bak
    remote_src: yes
  when:
    - not dhcp_agent_ini_bak.stat.exists

- name:  Backup file config metadata_agent.ini
  copy: 
    src: /etc/neutron/metadata_agent.ini
    dest: /etc/neutron/metadata_agent.ini.bak
    remote_src: yes
  when:
    - not metadata_agent_ini_bak.stat.exists

- name: Config neutron server
  template:
    src: neutron.conf.j2
    dest: /etc/neutron/neutron.conf
  notify: 
     - Restart neutron-server
     - Restart neutron-metadata-agent.service
     - Restart neutron-dhcp-agent.service
     - Restart neutron-openvswitch-agent.service
     - Restart  neutron-l3-agent.service
     - restart nova services
     - restart nova-scheduler services
     - restart nova-conductor services

- name: Config Modular Layer 2 (ML2) plug-in
  template:
    src: ml2_conf.ini.j2
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
  notify: 
     - Restart neutron-dhcp-agent.service
     - Restart neutron-openvswitch-agent.service


- name: Config the Open vSwitch agent
  template:
    src: openvswitch_agent.ini.j2
    dest: /etc/neutron/plugins/ml2/openvswitch_agent.ini
  notify:
    - Restart neutron-openvswitch-agent.service

- name: Configure the L3 agent
  template: 
    src: l3_agent.ini.j2
    dest: /etc/neutron/l3_agent.ini
  notify:
    - Restart  neutron-l3-agent.service

- name: Configure the DHCP agent
  template:
    src: dhcp_agent.ini.j2
    dest: /etc/neutron/dhcp_agent.ini
  notify:
     - Restart neutron-dhcp-agent.service

- name: Configure the metadata agent
  template:
    src: metadata_agent.ini.j2
    dest: /etc/neutron/metadata_agent.ini
  notify: 
     - Restart neutron-metadata-agent.service

- name: Check /etc/neutron/plugin.ini  existed
  stat:
    path: /etc/neutron/plugin.ini
  register: neutron_plugin_ini

- name: link file ml2 config
  shell:  ln -s /etc/neutron/plugins/ml2/ml2_conf.ini /etc/neutron/plugin.ini
  when:
     - not neutron_plugin_ini.stat.exists

- name: Chown group, user neutron
  file:
    path: "{{ item }}"
    owner: root
    group: neutron
    mode: u=rwX,g=rX
    recurse: yes
    state: directory
  with_items:
     - /etc/neutron

- name: Populate the database
  shell:  su -s /bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head" neutron
  run_once: true
  when: my_action == "deploy"


- meta: flush_handlers
