---
- name: Checking free port for Neutron Server
  wait_for:
    host: "{{ MGNT_IP }}"
    port: "9696"
    connect_timeout: 1
    timeout: 1
    state: stopped

- name: Checking free port for Neutron Server HAProxy
  wait_for:
    host: "{{ IP_VIP }}"
    port: "{{ neutron_server_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - enable_neutron | bool
    - enable_haproxy | bool