---
- name: Restart neutron-server
  systemd:
    state: restarted
    enabled: true
    name: neutron-server.service
  throttle: 1 

- name: Restart neutron-metadata-agent.service
  systemd:
    state: restarted
    enabled: true
    name: neutron-metadata-agent.service

- name: Restart neutron-dhcp-agent.service
  systemd:
    state: restarted
    enabled: true
    name: neutron-dhcp-agent.service

- name: Restart neutron-openvswitch-agent.service
  systemd:
    state: restarted
    enabled: true
    name: neutron-openvswitch-agent.service

- name: Restart neutron-l3-agent.service
  systemd:
    state: restarted
    enabled: true
    name:  neutron-l3-agent.service
