---
- name: Restart manila-api Services
  systemd:
    state: restarted
    enabled: true
    name: openstack-manila-api.service

- name: Restart manila-scheduler Services
  systemd:
     state: restarted
     enabled: true
     name: openstack-manila-scheduler.service

- name: Restart manila-share Services
  systemd:
      state: restarted
      enabled: true
      name: openstack-manila-share.service
