---
- name: enable_services pacemaker
  systemd:
    state: started
    enabled: true
    name: pacemaker
- name: enable_services corosync
  systemd:
    state: started
    enabled: true
    name: corosync
- name: enable_services haproxy
  systemd:
    state: restarted
    enabled: true
    name: haproxy
- name: start_pacemaker
  systemd:
    state: started
    enabled: true
    name: pcsd
