---
- name: disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no
    masked: yes
- name: disable networkmanager
  systemd:
    name: NetworkManager.service
    state: stopped
    enabled: no


- name: Reboot host
  reboot:
    connect_timeout: 5
    reboot_timeout: 3600
    pre_reboot_delay: 0
    post_reboot_delay: 0
    test_command: whoami

