---
# Day la playbook chinh thuc hien viec trien khai he thong OPS
## Duoi day la mot danh sach cac Play
## Cac Play nay se duoc thuc thi tren cac hosts hoac cac group duoc chi dinh
## Moi Play se thuc thi 1 role va duoc gan tag de phuc vu cho viec co the chay tung tag chi dinh bang tham so -t khi chay lenh
## Duoi moi Play co the duoc gan 1 dieu kien 


### Play gather fact thuc hien tren tat ca cac hosts va se duoc mac dinh chay dau playbook
- name: Garther_facts
  hosts: all
  gather_facts: true
  tasks:
    - name: Group hosts to determine when using --limit
      setup:


### Play nay se thuc thi role "openstack_facts" nham thuc hien cau hinh file /etc/hosts hoac set fact cac bien trong qua trinh chay playbook
- name: Openstack_facts
  hosts: all
  gather_facts: false
  tasks:
    - import_role:
        name: openstack_facts
  tags: always


### Play thuc thi role "baremental", thuc hien cai dat upgrade packages, cai dat repo,packages OPS, cau hinh selinux, disable firewalld,
#### Cai dat mot so tools can thiet, copy ssh-key, cau hinh hostname va reboot he thong
- name: Apply role baremental
  gather_facts: false
  become: true
  hosts: 
     - controller
     - compute
  roles:
    - { role: baremental,
        tags: baremental }
### Play thuc thi role "install_ntp", cai dat va cau hinh service chronyd
- name: Apply role chrony
  gather_facts: false
  become: true
  hosts: 
    - controller
    - compute
  roles:
    - { role: install_ntp,
        tags: install_ntp }

### Play thuc thi role "certificates", Thuc hien tao ra cac file cert su dung cho haproxy va service Octavia
- name: Apply role certificate
  gather_facts: false
  become: true
  hosts:
     - controller
     - deployment
     - compute
  roles:
    - { role: certificates,
        tags: certificates }
#        when: enable_ssl | bool 



### Play thuc thi role "install_docker", Thuc hien cai dat va cau hinh docker engine chi thuc hien tren controller
#### va enable_multisite co gia tri "yes"
- name: Apply role docker
  gather_facts: false
  become: true
  hosts: controller
  roles:
    - { role: install_docker,
        tags: install_docker,
        when: enable_multisite | bool }



### Play thuc thi role "install_mariadb", Thuc hien cai dat va cau hinh mariadb, se cau hinh cluster va healthcheck khi co 2 node controller tro len
- name: Apply role Mariadb
  gather_facts: false
  become: true
  hosts: controller
  roles:
    - { role: install_mariadb,
        tags: install_mariadb }

### Cai dat va cau hinh rabbitmq-server tren cac node controller, se cau hinh cluster khi co 2 node controller tro len 
- name: Apply role Rabbimq
  gather_facts: false
  become: true
  hosts: controller
  roles:
    - { role: install_rabbitmq,
        tags: install_rabbitmq }


### Cai dat va cau hinh memcache-server tren cac node controller
- name: Apply role Memcache
  gather_facts: false
  become: true
  hosts: controller
  roles:
    - { role: install_memcached,
        tags: install_memcached }


### Cai dat va cau hinh haproxy, se thuc hien cai dat khi gia tri cua enable_haproxy la "yes"
- name: Apply role HAproxy
  gather_facts: false
  become: true
  hosts: controller
  roles:
    - { role: install_haproxy,
        tags: install_haproxy, 
        when: enable_haproxy | bool }



### Cai dat va cau hinh pacemaker khi enable_pacemaker: "yes"
- name: Apply role Pacemaker
  gather_facts: false
  become: true
  hosts: controller
  roles:
    - { role: install_pacemaker,
        tags: install_pacemaker, 
        when: enable_pacemaker | bool }



- name: Apply role Keystone
  gather_facts: false
  become: true
  hosts: controller
  roles:
    - { role: install_keystone,
        tags: install_keystone,
        when: enable_keystone | bool }

- name: Apply role Glance
  gather_facts: false
  become: true
  hosts: controller
  roles:
    - { role: install_glance,
        tags: install_glance,
        when: enable_glance | bool }

- name: Apply role Placement
  gather_facts: false
  become: true
  hosts: controller
  roles:
    - { role: install_placement,
        tags: install_placement,
        when: enable_placement | bool }

- name: Apply role Nova
  gather_facts: false
  become: true
  hosts: controller
  roles:
    - { role: install_nova,
        tags: install_nova,
        when: enable_nova | bool }

- name: Apply role Nova_cell
  become: true
  gather_facts: false
  hosts: compute
  roles: 
    - { role: install_nova_cell,
        tags: install_nova_cell,
        when: enable_nova | bool }

- name: Apply role Neutron
  gather_facts: false
  become: true  
  hosts: controller
  roles:
    - { role: install_neutron,
        tags: install_neutron,
        when: enable_neutron |bool }

- name: Apply role Neutron_openvswitch
  become: true
  gather_facts: false
  hosts: compute
  roles:
    - { role: install_neutron_ovs,
        tags: install_neutron_ovs,
        when: enable_neutron | bool }

- name: Apply role Cinder
  become: true
  gather_facts: yes
  hosts: controller
  roles: 
    - { role: install_cinder,
        tags: install_cinder,
        when: enable_cinder | bool }


- name: Apply role Heat
  gather_facts: false
  become: true
  hosts: controller
  roles:
    - { role: install_heat,
        tags: install_heat,
        when: enable_heat | bool }

- name: Apply role Barbican
  gather_facts: false
  become: true
  hosts: controller
  roles:
    - { role: install_barbican,
        tags: install_barbican,
        when: enable_barbican | bool }

- name: Apply role Octavia
  gather_facts: false
  become: true
  hosts: controller
  roles:
    - { role: install_octavia,
        tags: install_octavia,
        when: enable_octavia | bool }

- name: Apply role Horizon
  gather_facts: false
  become: true
  hosts: controller
  roles:
    - { role: install_horizon,
        tags: install_horizon,
        when: enable_horizon | bool }


