---
- name: Checking free port for Heat API
  wait_for:
    host: "{{ management_ip_address }}"
    port: "{{ heat_api_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped

- name: Checking free port for Heat API CFN
  wait_for:
    host: "{{ management_ip_address }}"
    port: "{{ heat_api_cfn_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped

- name: Checking free port for Heat API HAProxy
  wait_for:
    host: "{{ ip_vip_address }}"
    port: "{{ heat_api_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - enable_heat | bool
    - enable_haproxy | bool

- name: Checking free port for Heat API CFN HAProxy
  wait_for:
    host: "{{ ip_vip_address }}"
    port: "{{ heat_api_cfn_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - enable_heat | bool
    - enable_haproxy | bool