---
- name: Restart ovs
  systemd:
    state: restarted
    enabled: true
    name: openvswitch


- name: Restart neutron-openvswitch service
  systemd:
    state: restarted
    enabled: true
    name: neutron-openvswitch-agent

- name: Restart service libvirtd
  systemd:
    state: restarted
    enabled: true
    name: libvirtd

- name: Restart service openstack-nova-compute
  systemd:
    state: restarted
    enabled: true
    name: openstack-nova-compute

- name: Restart network
  systemd:
     state: restarted
     name: network

- name: Restart neutron-l3-agent
  systemd:
      state: restarted
      name: neutron-l3-agent