---
- name: start docker
  systemd:
    state: started
    daemon_reload: yes
    name: docker

- name: Config file /etc/docker/daemon.json
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  notify: restart docker
