---
- name: Ensure docker.service.d directory exist
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: Ensure file http-proxy.conf exist
  template:
    src: http-proxy.conf.j2
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
  notify: restart docker 
