---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Install Docker.
  package:
    name: "{{ docker_package }}"
    state: present
  notify: restart docker

- include_tasks: config-docker.yml

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: "yes"

- include_tasks: config-proxy.yml
  when: enable_docker_proxy | bool

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers

- include_tasks: docker-users.yml
  when: docker_users | length > 0
