---
- include_tasks: config-docker.yml  

- include_tasks: config-proxy.yml
  when: enable_docker_proxy | bool

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers
