---
- name: Check /etc/neutron/neutron.conf.bak existed
  stat:
    path: /etc/neutron/neutron.conf.bak
  register: neutron_compute_conf_bak

- name: Check /etc/neutron/plugins/ml2/openvswitch_agent.ini.bak existed
  stat:
    path: /etc/neutron/plugins/ml2/openvswitch_agent.ini.bak
  register: openvswitch_compute_agent_ini_bak
  
- name: Backup file config neutron.conf
  copy:
   src: /etc/neutron/neutron.conf
   dest: /etc/neutron/neutron.conf.bak
   remote_src: yes
  when:
    - not neutron_compute_conf_bak.stat.exists

- name: Backup file openvswitch_agent.ini
  copy:
   src: /etc/neutron/plugins/ml2/openvswitch_agent.ini
   dest: /etc/neutron/plugins/ml2/openvswitch_agent.ini.bak
   remote_src: yes
  when:
    - not openvswitch_compute_agent_ini_bak.stat.exists

- name: Config file neutron.conf
  template:
    src: neutron.conf.j2
    dest: /etc/neutron/neutron.conf
    mode: 0640
    group: neutron
    owner: root
  notify:
      - Restart neutron-openvswitch service


- name: Config file OVS
  template:
    src: openvswitch_agent.ini.j2
    dest: /etc/neutron/plugins/ml2/openvswitch_agent.ini
    mode: 0640
    group: neutron
    owner: root
  notify:
      - Restart neutron-openvswitch service
      - Restart service libvirtd

- name: Config l3 agent
  template:
    src: l3_agent.ini.j2
    dest: /etc/neutron/l3_agent.ini
    mode: 0640
    group: neutron
    owner: root
  when: enable_neutron_dvr | bool
  notify:
      - Restart neutron-l3-agent

- name: Chown group, user neutron
  file:
    path: /etc/neutron
    owner: root
    group: neutron
    mode: u=rwX,g=rX
    recurse: yes
    state: directory
