---
- name: Restart ovs
  systemd:
    state: restarted
    enabled: true
    name: openvswitch
  throttle: 1 

- name: Restart neutron-openvswitch-agent service
  systemd:
    state: restarted
    enabled: true
    name: neutron-openvswitch-agent
  throttle: 1 

- name: Restart neutron-l3-agent service
  systemd:
    state: restarted
    enabled: true
    name: neutron-l3-agent
  throttle: 1 
  when: enable_neutron_dvr | bool