---
- name: Check /etc/openstack-dashboard/local_settings.bak existed
  stat:
    path: /etc/openstack-dashboard/local_settings.bak
  register: horizon_conf_bak

- name: Backup file config horizon
  copy:
   src: /etc/openstack-dashboard/local_settings
   dest: /etc/openstack-dashboard/local_settings.bak
   remote_src: yes
  when:
    - not horizon_conf_bak.stat.exists

- name: Edit the /etc/openstack-dashboard/local_settings file
  template:
    src: local_settings2.j2
    dest: /etc/openstack-dashboard/local_settings
    owner: root
    group: apache
    mode: 0640
  notify:
    - restart HTTPD
    - restart memcached

# - name: Config file /etc/httpd/conf.d/openstack-dashboard.conf
#   lineinfile:
#     path: /etc/httpd/conf.d/openstack-dashboard.conf
#     line: WSGIApplicationGroup %{GLOBAL}

- name: Config openstack dashboard.conf
  template:
    src: openstack-dashboard.conf.j2
    dest: /etc/httpd/conf.d/openstack-dashboard.conf
  notify:
    - restart HTTPD
    - restart memcached

- name: Redirecting to OpenStack Dashboard
  template:
     src: index.j2
     dest: /var/www/html/index.html
  notify:
    - restart HTTPD
    - restart memcached

- name: Update cinder-client
  copy:
    src: cinder.py
    dest: /usr/share/openstack-dashboard/openstack_dashboard/api/cinder.py
  notify:
    - restart HTTPD
    - restart memcached



