---
- name: restart HTTPD
  systemd:
    state : restarted
    enabled: true
    name: httpd.service
  throttle: 1

- name: restart memcached
  systemd:
    state : restarted
    enabled: true
    name: memcached.service
  throttle: 1