---
- name: Create user Glance
  os_user:
    name: glance
    auth: "{{ openstack_auth }}"
    password: "{{ glance_pass }}"
    domain: default
    region_name: "{{ region_name }}"
    ca_cert: "{{ openstack_cacert }}"
  run_once: true
  when: region_name == region_main_site

- name: Create role for user glance
  os_user_role:
    auth: "{{ openstack_auth }}"
    user: glance
    role: admin
    project: service
    region_name: "{{ region_name }}"
    ca_cert: "{{ openstack_cacert }}"
    state: present
  run_once: true
  when: region_name == region_main_site

- name: Create Image service
  os_keystone_service:
    name: glance
    auth: "{{ openstack_auth }}"
    service_type: image
    region_name: "{{ region_name }}"
    description: Openstack Image
    ca_cert: "{{ openstack_cacert }}"
  run_once: true
  when: region_name == region_main_site

- name: Create endpoint
  os_keystone_endpoint:
     auth: "{{ openstack_auth }}"
     service: glance
     region_name: "{{ region_name }}"
     endpoint_interface: "{{ item }}"
     url: "{{ keystone_protocol }}://{{ ip_vip_address }}:{{ glance_api_port }}"
     region: "{{ region_name }}"
     ca_cert: "{{ openstack_cacert }}"
     state: present
  with_items:
    - public
    - admin
    - internal
  run_once: true
  when: region_name == region_main_site

- name: Create endpoint other site
  os_keystone_endpoint:
     auth: "{{ openstack_auth }}"
     service: glance
     endpoint_interface: "{{ item }}"
     url: "{{ keystone_protocol }}://{{ ip_vip_address }}:{{ glance_api_port }}"
     region: "{{ region_name }}"
     region_name: "{{ region_main_site }}"
     ca_cert: "{{ openstack_cacert }}"
     state: present
  with_items:
    - public
    - admin
    - internal
  run_once: true
  vars:
     ansible_port: "{{ ssh_port_other_site }}"
  delegate_to: "{{ other_site_ip_list[0] }}"
  when: region_name != region_main_site
