---
- name: Create user Glance
  os_user:
    name: glance
    auth: "{{ openstack_auth }}"
    password: "{{ glance_pass }}"
    domain: default
    ca_cert: "{{ openstack_cacert }}"
  run_once: true

- name: Create role for user glance
  os_user_role:
    auth: "{{ openstack_auth }}"
    user: glance
    role: admin
    project: service
    ca_cert: "{{ openstack_cacert }}"
    state: present
  run_once: true

- name: Create Image service
  os_keystone_service:
    name: glance
    auth: "{{ openstack_auth }}"
    service_type: image
    description: Openstack Image
    ca_cert: "{{ openstack_cacert }}"
  run_once: true


- name: Create endpoint
  os_keystone_endpoint:
     auth: "{{ openstack_auth }}"
     service: glance
     endpoint_interface: "{{ item }}"
     url: "{{ keystone_protocol }}://{{ IP_VIP }}:9292"
     region: "{{ REGION }}"
     ca_cert: "{{ openstack_cacert }}"
     state: present
  with_items:
    - public
    - admin
    - internal
  run_once: true



