---
- name: Create user Placement
  os_user:
    name: placement
    auth: "{{ openstack_auth }}"
    password: "{{ placement_pass }}"
    domain: default
    ca_cert: "{{ openstack_cacert }}"
    region_name: "{{ region_name }}"
  run_once: true
  when: region_name == region_main_site

- name: Create role for user Placement
  os_user_role:
    auth: "{{ openstack_auth }}"
    user: placement
    role: admin
    project: service
    ca_cert: "{{ openstack_cacert }}"
    region_name: "{{ region_name }}"
    state: present
  run_once: true
  when: region_name == region_main_site

- name: Create Placement service
  os_keystone_service:
    name: placement
    auth: "{{ openstack_auth }}"
    service_type: placement
    ca_cert: "{{ openstack_cacert }}"
    region_name: "{{ region_name }}"
    description: Placement API
  run_once: true
  when: region_name == region_main_site

- name: Create endpoint for Placement
  os_keystone_endpoint:
     auth: "{{ openstack_auth }}"
     service: placement
     endpoint_interface: "{{ item }}"
     url: "{{ keystone_protocol }}://{{ ip_vip_address }}:{{ placement_port }}"
     region: "{{ region_name }}"
     region_name: "{{ region_name }}"
     ca_cert: "{{ openstack_cacert }}"
     state: present
  with_items:
    - public
    - admin
    - internal
  run_once: true
  when: region_name == region_main_site

- name: Create endpoint for Placement other site
  os_keystone_endpoint:
     auth: "{{ openstack_auth }}"
     service: placement
     endpoint_interface: "{{ item }}"
     url: "{{ keystone_protocol }}://{{ ip_vip_address }}:{{ placement_port }}"
     region: "{{ region_name }}"
     region_name: "{{ region_main_site }}"
     ca_cert: "{{ openstack_cacert }}"
     state: present
  with_items:
    - public
    - admin
    - internal
  run_once: true
  vars:
     ansible_port: "{{ ssh_port_other_site }}"
  delegate_to: "{{ other_site_ip_list[0] }}"
  when: region_name != region_main_site
