---
- name: Check /etc/cinder/cinder.conf.bak existed
  stat:
    path: /etc/cinder/cinder.conf.bak
  register: cinder_conf_bak

- name: Backup file config cinder.conf
  copy:
    src: /etc/cinder/cinder.conf
    dest: /etc/cinder/cinder.conf.bak
    remote_src: yes
  when: 
    - not cinder_conf_bak.stat.exists

- name: Config file cinder.conf
  template:
    src: cinder.conf.j2
    dest: /etc/cinder/cinder.conf
  notify:
     - restart service Nova-API
     - restart Service Cinder-API
     - restart Service Cinder scheduler
     - restart Service Cinder Volume
     - restart service Cinder Backup

# - name: Chown group, user cinder
#   file:
#     path: "{{ item }}"
#     owner: root
#     group: cinder
#     mode: u=rwX,g=rX
#     recurse: yes
#     state: directory
#   with_items:
#      - /etc/cinder

- name: Populate the Block Storage service database
  shell: 
     su -s /bin/sh -c "cinder-manage db sync" cinder
  run_once: true
  when: my_action == "deploy"
