---
- name: Install Cinder Packages
  yum:
    name: openstack-cinder

- name: Install packages to setup lvm
  yum:
    name: "{{ cinder_lvm_packages }}"
  when:
     - enable_cinder_backend_lvm | bool
