---
- name: Checking free port for Barbican API
  wait_for:
    host: "{{ MGNT_IP }}"
    port: "{{ barbican_api_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped


- name: Checking free port for Barbican API HAProxy
  wait_for:
    host: "{{ IP_VIP }}"
    port: "{{ barbican_api_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - enable_barbican | bool
    - enable_haproxy | bool