---
- name: Enable repo HA
  dnf:
    name: pcs
    enablerepo: ha
    #HighAvailability

- name: Update all packages in HighAvailability repo
  dnf:
    name: "*"
    state: latest
    enablerepo: ha
    #HighAvailability


- name: install pacemaker
  yum: 
   name: '{{ pacemaker_packages }}'
  notify: 
    - stop_haproxy

- meta: flush_handlers

- name: set hacluster password
  shell: echo {{ corosync_pass }} | passwd --stdin hacluster
  check_mode: no
  failed_when: false
  changed_when: false


- name: start pcsd
  systemd:
    state: started
    enabled: yes
    name: pcsd
  notify:
    - enable_services corosync
    - enable_services pacemaker
    - Start haproxy
    - start_pacemaker

- name: Checking if all hosts are in cluster
  changed_when: false
  failed_when: false
  check_mode: no
  script: pacemakernodes.py
  register: pcs_status

- include_tasks: config_cluster.yml
  when: pcs_status.stdout | int != groups['controller'] | length | int
