---
- name: start rabbitmq-server.service
  systemd:
     name: rabbitmq-server.service
     state: started
     enabled: yes
     daemon_reload: yes

- name: restart rabbitmq-server
  systemd:
     name: rabbitmq-server.service
     state: restarted
     enabled: yes
     daemon_reload: yes
