---
- name: stop_haproxy
  systemd:
    state: stopped
    enabled: true
    name: haproxy

- name: restart_haproxy
  systemd:
    state: restarted
    enabled: true
    name: haproxy
  throttle: 1

- name: Restart rsyslog
  systemd: 
     state: restarted
     enabled: true
     name: rsyslog
