---
- name: stop_haproxy
  systemd:
    state: stopped
    enabled: true
    name: haproxy

- name: restart_rsyslog
  systemd:
    state: restarted
    enabled: true
    name: rsyslog

- name:  Compile Haproxy with System
  make:
    chdir: "{{ ansible_deploy_files }}/haproxy-2.0.7"
    target: install

- name:  Compile Haproxy with Systemd
  make:
    chdir: "{{ ansible_deploy_files }}/haproxy-2.0.7"
    params:
       TARGET: linux-glibc
       USE_PCRE: 1
       USE_OPENSSL: 1
       USE_ZLIB: 1
       USE_CRYPT_H: 1
       USE_LIBCRYP: 1