---
- name: Config /etc/hosts
  template:
    src: hosts.j2
    dest: "/etc/hosts"
  when: not inventory_hostname in groups['deployment']

- name: show all ip management 
  set_fact:
    all_management_ip: "{% for i in groups['controller'] %}{{ hostvars[i]['ansible_host'] }}{% if not loop.last %},{% endif %}{% endfor %}"

- name: Set all ip management to a list
  set_fact:
    list_management_ip: "{{ all_management_ip.split(',') }}"

- name: show all hostname_short
  set_fact:
    all_hostname: "{% for i in groups['controller'] %}{{ hostvars[i]['inventory_hostname_short'] }}{% if not loop.last %},{% endif %}{% endfor %}"
  
- name: Set all hostname_short to a list
  set_fact:
     list_hostname_short: "{{ all_hostname.split(',') }}"

- name: Check Bridge provider config
  stat: 
    path: /etc/sysconfig/network-scripts/ifcfg-br-provider
  register: br_provider

- name: Find EXTERNAL ip 
  set_fact:
    external_ip_address: "{{ hostvars[inventory_hostname]['ansible_br_provider']['ipv4']['address'] }}"
  when:
   - br_provider.stat.exists

- name: Find External netmask
  set_fact:
    external_netmask: "{{ hostvars[inventory_hostname]['ansible_br_provider']['ipv4']['netmask'] }}"
  when:
   - br_provider.stat.exists


- name: Set fact horizon domain 
  set_fact: 
     horizon_domain: "{{ domain_website | default(ip_vip_address) }}"
  
- name: Set fact nova vncproxy domain
  set_fact:
     novavnc_domain: "{{ domain_vnc_main_site | default(ip_vip_address) }}"

