---
- name: Check /etc/libvirt/libvirtd.conf.bak existed
  stat:
    path: /etc/libvirt/libvirtd.conf
  register: libvirtd_conf

- name: Check /etc/sysconfig/libvirtd.bak existed
  stat:
    path: /etc/sysconfig/libvirtd.bak
  register: libvirtd_sysconfig

- name: Config Libvirt
  template:
      src: libvirtd.conf.j2
      dest: /etc/libvirt/libvirtd.conf

- name: Config /etc/sysconfig/libvirtd
  template:
    src: libvirtd_sysconfig.j2
    dest: /etc/sysconfig/libvirtd
  notify:
    - Restart libvirtd
 
- name: Mask libvirtd.socket
  systemd:
     masked: yes
     enabled: no
     state: stopped
     name: libvirtd.socket

- name: Mask libvirtd-admin.socket
  systemd:
     masked: yes
     enabled: no
     state: stopped
     name: libvirtd-admin.socket

- name: Mask libvirtd-ro.socket
  systemd:
     masked: yes
     enabled: no
     state: stopped
     name: libvirtd-ro.socket

- name: Mask libvirtd-tcp.socket
  systemd:
     masked: yes
     enabled: no
     state: stopped
     name: libvirtd-tcp.socket

- name: Mask libvirtd-tls.socket
  systemd:
     masked: yes
     enabled: no
     state: stopped
     name: libvirtd-tls.socket
