---
#
#
# Cau hinh nova service
# flush_handlers la  thuc hien cac notify truoc do ( restart service openstack-nova-compute va libvirtd )
# Tao file secret.xml tai node compute
# Tim xem co ton tai secret key nao khong
# Xoa neu ton tai secret key 
# Define secret-key tu file secret.xml da tao
# Check su ton tai file key cua client.cinder vao bien client_cinder_key
# Add client.cinder key vao KVM
- name: Check /etc/nova/nova.conf.bak existed
  stat:
    path: /etc/nova/nova.conf.bak
  register: nova_compute_conf_bak

- name: Backup file config nova.conf
  copy:
   src: /etc/nova/nova.conf
   dest: /etc/nova/nova.conf.bak
   remote_src: yes
  when:
    - not  nova_compute_conf_bak.stat.exists
    
- name: Config file nova.conf
  template:
    src: nova.conf.j2
    dest: /etc/nova/nova.conf
  notify: 
    - Restart libvirtd
    - Restart service openstack-nova-compute

- meta: flush_handlers

- name: Create secret file key
  template:
    src: secret.xml.j2
    dest: secret.xml
  when:
    - enable_ceph | bool

- name: Find existed key
  shell: virsh secret-list | egrep client.cinder | awk '{print $1}'
  register: secret_list
  changed_when: false
  when:
    - enable_ceph | bool

- name: Delete existed key
  command: virsh secret-undefine "{{ secret_list.stdout }}"
  changed_when: false
  when:
    - enable_ceph | bool
    - secret_list.stdout != ""

- name: Virsh file secret.xml
  shell: virsh secret-define --file secret.xml
  when:
    - enable_ceph | bool


- name: Check cinder keyring file exist
  stat:
    path: /root/client.cinder.key
  register: client_cinder_key
  when:
    - enable_ceph | bool


- name: Combine secret key with Ceph key
  shell: virsh secret-set-value --secret {{ openstack_uuid }} --base64 $(cat client.cinder.key)
  when:
    -  enable_ceph | bool
    -  client_cinder_key.stat.exists
