---
- name: Check /etc/nova/nova.conf.bak existed
  stat:
    path: /etc/nova/nova.conf.bak
  register: nova_compute_conf_bak

- name: Backup file config nova.conf
  copy:
   src: /etc/nova/nova.conf
   dest: /etc/nova/nova.conf.bak
   remote_src: yes
  when:
    - not nova_compute_conf_bak.stat.exists
    
- name: Config file nova.conf
  template:
    src: nova.conf.j2
    dest: /etc/nova/nova.conf
    mode: 0640
    group: nova
    owner: root
  notify: 
    - Restart libvirtd
    - Restart service openstack-nova-compute

- name: Chown group, user nova
  file:
    path: "/etc/nova"
    owner: root
    group: nova
    mode: u=rwX,g=rX
    recurse: yes
    state: directory
     
- meta: flush_handlers
