---
- name: Restart service libvirtd
  systemd: 
    state: restarted
    enabled: true
    name: libvirtd

- name: Restart service openstack-nova-compute
  systemd:
    state: restarted
    enabled: true
    name: openstack-nova-compute


