---
- name: Create a directory for store cert
  file:
     path: /etc/ssl/private
     state: directory
     mode: 0755
  when:
     - group_names != hostvars[groups['deployment'][0]]['group_names']

- name: Copy cert dir to other node
  synchronize:
     src: "{{ deploy_directory }}/private"
     dest: "/etc/ssl/"
     mode: pull
     dest_port: "{{ hostvars[groups['deployment'][0]]['ansible_port'] }}"
  delegate_to: "{{ item }}"  
  with_items:   
    - "{{ groups['all'] }}"
  when:
     - group_names == hostvars[groups['deployment'][0]]['group_names']

- name: Permission CA directory
  file:
    path: "/etc/ssl/private"
    mode: 0755
    state: directory

- name: Enable the dynamic CA configuration feature
  shell: update-ca-trust force-enable
  check_mode: no
  failed_when: false
  changed_when: false
  when:
     - group_names != hostvars[groups['deployment'][0]]['group_names']

- name: Copy Cert to Trusted CA in OS
  copy: 
     src: "/etc/ssl/private/{{ item }}.crt"
     dest: /etc/pki/ca-trust/source/anchors/
     remote_src : yes
     mode: "0644"
  with_items:
        - '{{ cafile_name }}'
  when:
     - group_names != hostvars[groups['deployment'][0]]['group_names']

- name: extract cert
  shell: update-ca-trust extract
  check_mode: no
  failed_when: false
  changed_when: false
  when:
     - group_names != hostvars[groups['deployment'][0]]['group_names']
