---
- name: Check cert already exist on controller and compute node
  stat:
    path: "{{ ansible_deploy_files }}/private"
  register: ca_cert_ops

- include_tasks: generate.yml
  when: 
     - enable_ssl | bool 
     - not ca_cert_ops.stat.exists

- name: Create a directory for store cert
  file:
     path: /etc/ssl/private
     state: directory
  when:
     - group_names != hostvars[groups['deployment'][0]]['group_names']

- name: Copy to controller node
  copy:
    src: "{{ ansible_deploy_files }}/private/{{ item }}.pem"
    dest: "/etc/ssl/private/{{ item }}.pem"
    mode: "0655"
  with_items:
       - '{{ cafile_name }}'
  when:
     - group_names  == hostvars[groups['controller'][0]]['group_names'] 

- name: Copy to compute node
  copy:
    src: "{{ ansible_deploy_files }}/private/{{ item }}.pem"
    dest: "/etc/ssl/private/{{ item }}.pem"
    mode: "0655"
  with_items:
       - '{{ cafile_name }}'
  when:
     - group_names  == hostvars[groups['compute'][0]]['group_names']

- name: Check if ocatvia's certs exist
  stat:
    path: "{{ ansible_deploy_files }}/octavia_certs"
  register: octavia_certs

- include_tasks: octavia_cert.yml 
  when:
    - enable_octavia | bool
    - not octavia_certs.stat.exists

- include_tasks: copy_octavia_certs.yml
  when:
    - enable_octavia | bool