---
- include_tasks: generate.yml
  when: enable_ssl | bool 
- name: Check if ocatvia's certs exist
  stat:
    path: "{{ ansible_deploy_files }}/octavia_certs"
  register: octavia_certs
- include_tasks: octavia_cert.yml 
  when:
    - enable_octavia | bool
    - not octavia_certs.stat.exists

- include_tasks: copy_octavia_certs.yml
  when:
    - enable_octavia | bool