---
- name: Ensuring private internal directory exist
  file:
    path: "{{ deploy_directory }}/private"
    state: "directory"
    mode: 0755

- name: Creating external SSL configuration file
  template:
     src: "openssl.cnf.j2"
     dest: "{{ deploy_directory }}/private/openssl.cnf"
     mode: "0660"

- name: Creating Server Certificate
  command: openssl req -x509 -nodes -config {{ deploy_directory }}/private/openssl.cnf -days 3650 -newkey rsa:2048 -keyout {{ deploy_directory }}/private/{{ item }}.key -out {{ deploy_directory }}/private/{{ item }}.crt
  with_items:
     - "{{ cafile_name }}"


- name: Create pem file on deployment node
  shell: cat {{ deploy_directory }}/private/{{ item }}.crt {{ deploy_directory }}/private/{{ item }}.key > {{ deploy_directory }}/private/{{ item }}.pem
  with_items:
     - '{{ cafile_name }}'
