---
- name: Ensuring private internal directory exist
  file:
    path: "{{ ansible_deploy_files }}/private"
    state: "directory"
    recurse: yes
    mode: "0770"
  when:
    -  group_names  == hostvars[groups['deployment'][0]]['group_names']
- name: Creating external SSL configuration file
  template:
     src: "openssl.cnf.j2"
     dest: "{{ ansible_deploy_files }}/private/openssl.cnf"
     mode: "0660"
  when:
    -  group_names  == hostvars[groups['deployment'][0]]['group_names']

- name: Creating  Server Certificate
  command: openssl req -x509 -nodes -config {{ ansible_deploy_files }}/private/openssl.cnf -days 3650 -newkey rsa:2048 -keyout {{ ansible_deploy_files }}/private/{{ item }}.key -out {{ ansible_deploy_files }}/private/{{ item }}.crt
  with_items:
     - "{{ cafile_name }}"
  when: 
     -  group_names  == hostvars[groups['deployment'][0]]['group_names']

- name: Create pem file on deployment node
  shell: cat {{ ansible_deploy_files }}/private/{{ item }}.crt {{ ansible_deploy_files }}/private/{{ item }}.key > {{ ansible_deploy_files }}/private/{{ item }}.pem
  with_items:
     - '{{ cafile_name }}'
  when:
     - group_names  == hostvars[groups['deployment'][0]]['group_names']

- name: Create a directory for store cert
  file:
     path: /etc/ssl/private
     state: directory
  when:
     - group_names != hostvars[groups['deployment'][0]]['group_names']


      