# ---
# - name: Ucommenting a line in /etc/rsyslog.conf.
#   replace:
#       path: /etc/rsyslog.conf
#       regexp: '#\$ModLoad imudp'
#       replace: '$ModLoad imudp'
# - name: Ucommenting a line in /etc/rsyslog.conf.
#   replace:
#       path: /etc/rsyslog.conf
#       regexp: '#\$UDPServerRun 514'
#       replace: '$UDPServerRun 514' 
# - name: Insert a line at the end of a file /etc/rsyslog.conf.
#   lineinfile:
#        path: /etc/rsyslog.conf
#        line: $UDPServerAddress 127.0.0.1
# - name: Config rsyslog for haproxy
#   template:
#     src: haproxy.cnf.j2
#     dest: /etc/rsyslog.d/haproxy.conf
#   notify:
#      - restart_rsyslog 
