---
- name: start mariadb
  systemd:
    state: started
    name: mariadb
    enabled: yes

- name: stop mariadb
  systemd:
    state: stopped
    name: mariadb
    enabled: yes

- name: restart mariadb
  systemd:
    state: restarted
    name: mariadb

- name: Ensure there are no packages mariadb
  yum: 
   name:
      - mariadb-common*
      - mariadb-config*
      - MariaDB-common
      - mariadb-libs
   state: removed   