---
- name: Ensure mariadb stopped
  systemd:
    name: mariadb
    state: stopped	
- name: Config Mariadb Cluster
  template:
     src: cluster.cnf.j2
     dest: /etc/my.cnf.d/cluster.cnf
  when:
     - groups['controller'] | length  > 1 
- name: Config file replica.cnf
  template:
    src: replica.cnf.j2
    dest: /etc/my.cnf.d/replica.cnf
  when:
    - groups['controller'] | length  > 1

- name: Create Galera Cluster
  shell: /usr/bin/galera_new_cluster
  when:
    - inventory_hostname_short ==  hostvars[groups['controller'][0]]['inventory_hostname_short']	
- name: Start mariadb 
  systemd:
    state: started
    enabled: true
    name: mariadb
