---
# Dung service mariadb tren tat ca cac node
# Cau hinh mariadb cluster
# Cau hinh mariadb replicate
# Khoi tao cum cluster, chi thuc hien tren hosts dau tien duoc khai bao trong group [controller]
# Khoi dong service Mariadb tren tat ca cac node controller
# Cau hinh cho viec tai khoi tao cum cluster

- name: Ensure mariadb stopped
  systemd:
    name: mariadb
    state: stopped
    
- name: Config Mariadb Cluster
  template:
     src: cluster.cnf.j2
     dest: /etc/my.cnf.d/cluster.cnf
  when:
     - groups['controller'] | length  > 1 
- name: Config file replica.cnf
  template:
    src: replica.cnf.j2
    dest: /etc/my.cnf.d/replica.cnf
  when:
    - groups['controller'] | length  > 1

- name: Create Galera Cluster
  shell: /usr/bin/galera_new_cluster
  when:
    - inventory_hostname_short ==  hostvars[groups['controller'][0]]['inventory_hostname_short']
    - groups['controller'] | length  > 1
    
- name: Start mariadb 
  systemd:
    state: started
    enabled: true
    name: mariadb


- name: Set rebuild Cluster after reboot
  lineinfile:
     path: /var/lib/mysql/grastate.dat
     regexp: '^safe_to_bootstrap: 0'
     insertafter: '^#safe_to_bootstrap: 0'
     line: 'safe_to_bootstrap: 1'
  when:
    - groups['controller'] | length  > 1