---
- name: Update packages for Servers
  yum:
     name: '*'
     state: latest

- name: install mariadb
  dnf:
    name: '@mariadb:10.3'

- name: Install mariadb-galera
  dnf:
    name: mariadb-server-galera
  when:
     - groups['controller'] | length  > 1
    
- name: Install depend packages
  yum: 
    name: '{{ mariadb_packages }}'
    
- name: Config Mariadb if only have one node controller
  template:
    src: openstack.cnf.j2
    dest: /etc/my.cnf.d/mariadb-server.cnf
  when:
     - groups['controller'] | length  < 2 

- name: Comment bind-address
  replace:
    dest: /etc/my.cnf.d/galera.cnf
    regexp: '^bind-address=0.0.0.0'
    replace: 'bind-address={{ management_ip_address }}'
  when:
     - groups['controller'] | length  > 1

- name: Add LimitNOFILE=infinity
  lineinfile:
    dest: "/usr/lib/systemd/system/mariadb.service"
    insertafter: 'Type=simple'
    line: "LimitNOFILE=infinity"

- name: Start mariadb
  systemd:
    name: mariadb
    enabled: true
    state: started
    daemon_reload: yes

- name: check status mariadb
  shell: mysql -uroot -p{{ mariadb_pass }} -e "SHOW STATUS LIKE 'wsrep_cluster_size'" | egrep  wsrep_cluster_size | awk '{print $2}'
  check_mode: no
  failed_when: false
  changed_when: false
  register: mariadb_cluster_status

- name: Config HealthCheck for Mariadb
  block:
   - name: copy file to /usr/local/bin
     copy:
       src: clustercheck
       dest: /usr/local/bin/clustercheck
       mode: 0777

   - name: config xinetd
     template:
       src: mysqlchk.j2
       dest: /etc/xinetd.d/mysqlchk
     notify:
       - Restart service xinetd

   - name: config mysqlchk services
     lineinfile:
       path: /etc/services
       line: mysqlchk 9200/tcp # MySQL check
  when:
      - groups['controller'] | length > 1

- include_tasks: config_cluster.yml
  when:
    - mariadb_cluster_status.stdout | int != groups['controller'] | length | int
    - groups['controller'] | length > 1


- name: Check Mariadb already have Password
  command: mysql -uroot -p{{ mariadb_pass }} -e"show databases;"
  register: checkpassmariadb
  check_mode: no
  failed_when: false
  changed_when: false

- include_tasks: config_access_root.yml
  when:
    - checkpassmariadb.rc == 1

- name: Set rebuild Cluster after reboot
  lineinfile:
     path: /var/lib/mysql/grastate.dat
     regexp: '^safe_to_bootstrap: 0'
     insertafter: '^#safe_to_bootstrap: 0'
     line: 'safe_to_bootstrap: 1'
  when:
    - groups['controller'] | length > 1