---
- name: Create certs directory
  file:
    path: "/etc/octavia/certs"
    state: directory
    owner: octavia
    group: octavia
    mode: 0700

- name: Copy server ca key
  copy:
    src: "{{ ansible_deploy_files }}/octavia_certs/server_ca/private/server_ca.key.pem"
    dest: "/etc/octavia/certs/server_ca.key.pem"
    remote_src: yes
    owner: octavia
    group: octavia
    mode: 0700

- name: Copy server CA cert
  copy:
    src: "{{ ansible_deploy_files }}/octavia_certs/server_ca/certs/server_ca.cert.pem"
    dest: "/etc/octavia/certs/server_ca.cert.pem"
    remote_src: yes
    owner: octavia
    group: octavia
    mode: 0644

- name: Copy Client CA cert
  copy:
    src: "{{ ansible_deploy_files }}/octavia_certs/client_ca/certs/client_ca.cert.pem"
    dest: "/etc/octavia/certs/client_ca.cert.pem"
    remote_src: yes
    owner: octavia
    group: octavia
    mode: 0644

- name: Copy client.cert-and-key.pem
  copy: 
    src: "{{ ansible_deploy_files }}/octavia_certs/client_ca/private/client.cert-and-key.pem"
    dest: "/etc/octavia/certs/client.cert-and-key.pem"
    remote_src: yes
    owner: octavia
    group: octavia
    mode: 0700