---
- name: Enable and Restart Octavia-api Services
  systemd:
    state: restarted
    enabled: true
    name: octavia-api.service


- name: Enable and Restart Octavia-health manager Services
  systemd:
     state: restarted
     enabled: true
     name: octavia-health-manager.service

- name: Enable and Restart Octavia-housekeeping Services
  systemd:
      state: restarted
      enabled: true
      name: octavia-housekeeping.service

- name: Enable and Restart Octavia-worker Services
  systemd:
      state: restarted
      enabled: true
      name: octavia-worker.service