---
- name: restart chrony.service
  systemd:
    state: restarted
    enabled: yes
    name: chronyd.service

- name: Restart crond
  systemd:
     state: restarted
     enabled: true
     name: crond
