---
- name: Show status HTTPD
  debug:
    msg: "HTTPD status is {{ services_status.ansible_facts.services['httpd.service'].state }}"

- name: HTTPD has problem
  fail:
    msg: "HTTPD status is {{ services_status.ansible_facts.services['httpd.service'].state }} please check your system"
  when: services_status.ansible_facts.services['httpd.service'].state != "running"
  ignore_errors: True

- name: Check Keystone
  shell: |
     source /root/admin-openrc-{{ region_name }}
     openstack endpoint list
  check_mode: no
  failed_when: false
  changed_when: false
  register: command_check_keystone

- name: Keystone ERROR
  fail:
    msg: " Connect to Keystone Failed !! Please check by command 'openstack endpoint list --debug'"
  when: command_check_keystone.rc != 0
  ignore_errors: True