---
- name: Add user 'keystone' with a bash shell
  user:
    name: keystone
    shell: /bin/bash
- name: Create SSH config directory for keystone
  file:
    path: /var/lib/keystone/.ssh
    state: directory

- name: Config SSH key for user Keystone
  copy:
    src: /root/.ssh/id_rsa
    dest: /var/lib/keystone/.ssh/id_rsa
    mode: 0400

- name: Config  user keystone id_rsa.pub
  copy:
    src: /root/.ssh/id_rsa.pub
    dest: /var/lib/keystone/.ssh/id_rsa.pub
    mode: 0400

- name: Config user keystone authorized_keys
  copy:
    src: /root/.ssh/id_rsa.pub
    dest: /var/lib/keystone/.ssh/authorized_keys
    mode: 0400

- name: config ssh for user keystone
  template:
    src: config-ssh.j2
    dest: /var/lib/keystone/.ssh/config
    mode: 0600

- name: Chmod ssh keystone directory
  file:
    path: /var/lib/keystone/.ssh/
    recurse: yes

- name: Chown ssh keystone
  file:
    path: /var/lib/keystone/.ssh
    owner: keystone
    group: keystone
    recurse: yes
- name: config Keystone  HTTPD
  template:
   src: wsgi-keystone.conf.j2
   dest: /etc/httpd/conf.d/wsgi-keystone.conf
  notify:
    - restart service httpd
    - sleep for 10s and continue with play
    - Create script test system
- name: config HTTPD
  template:
   src: httpd.conf.j2
   dest: /etc/httpd/conf/httpd.conf
  notify:
    - restart service httpd
    - sleep for 10s and continue with play
    - Create script test system
