---
- name: Create container config directory
  file:
    path: /etc/container/hcm-mariadb-{{ inventory_hostname_short }}
    state: directory

- name: Create file config for container Mariadb
  template:
    src: hcm-mariadb-controller.j2
    dest: /etc/container/hcm-mariadb-{{ inventory_hostname_short }}/server.cnf

- name: Config iptables
  command: iptables -P FORWARD ACCEPT
  changed_when: false
  when: my_action == "deploy"

- name: Login Docker
  docker_login:
    username: "{{ dockerhub_username }}"
    password: "{{ dockerhub_pass }}"

- name: Create Container Mariadb for Keystone
  docker_container:
    name: hcm-mariadb-{{ inventory_hostname_short }}
    restart_policy: always
    env:
       DEBUG: "YES"
       MYSQL_ROOT_PASSWORD: "{{ mariadb_pass }}"
    ports:
      - "{{ management_ip_address }}:{{ mysql_container_slave_port }}:{{ mysql_cluster_port }}"
    volumes:
      - /etc/container/hcm-mariadb-{{ inventory_hostname_short }}/server.cnf:/etc/mysql/conf.d/server.cnf
    pull: yes
    image: mariadb:{{ mariadb_version }} 

- name: Wait until listening on port {{ mysql_container_slave_port }} 
  wait_for:
    host: "{{ ip_vip_address }}"
    port: "{{ mysql_container_slave_port }}"
    delay: 10
    msg: " Please check Resource IP VIP"
    timeout: 15