---
- include_tasks: create_containerDB.yml
  when: 
    - region_name != region_main_site

- include_tasks: config_replicate_container.yml
  when:
    - region_name != region_main_site

- include_tasks: bootstrap.yml
  when:
    - region_name == region_main_site

- include_tasks: install.yml

- include_tasks: config_httpd.yml

- include_tasks: config_keystone.yml

- include_tasks: config_rotate_key.yml
  when: groups['controller'] | length > 1

- include_tasks: register.yml
