- name: Checking free port for Keystone Admin
  wait_for:
    host: "{{ management_ip_address }}"
    port: "{{ keystone_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped

- name: Checking free port for Keystone Admin HAProxy
  wait_for:
    host: "{{ ip_vip_address }}"
    port: "{{ keystone_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - enable_keystone | bool
    - enable_haproxy | bool
    