- name: Checking free port for Keystone Admin
  wait_for:
    host: "{{ MGNT_IP }}"
    port: "{{ keystone_admin_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped


- name: Checking free port for Keystone Admin HAProxy
  wait_for:
    host: "{{ IP_VIP }}"
    port: "{{ keystone_admin_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - enable_keystone | bool
    - enable_haproxy | bool
    