---
- name: Bootstrap the Identity service
  shell: keystone-manage bootstrap --bootstrap-password {{ admin_pass }} --bootstrap-admin-url {{ keystone_url }} --bootstrap-internal-url {{ keystone_url }} --bootstrap-public-url {{ keystone_url }} --bootstrap-region-id {{ region_name }}
  check_mode: no
  failed_when: false
  changed_when: false
  run_once: true
  when: region_name == region_main_site

- name: Create OpenStack client environment scripts
  template:
     src: admin-openrc.j2
     dest: "/root/admin-openrc-{{ region_name }}"
     mode: 0751
  
- name: Create project service Openstack
  os_project:
     name: service
     auth: "{{ openstack_auth }}"
     description: Openstack Service Project
     domain: default
     region_name: "{{ region_name }}"
     state: present
     ca_cert: "{{ openstack_cacert }}"
  run_once: true
  when: region_name == region_main_site

- name: Create project demo
  os_project:
     name: demo
     auth: "{{ openstack_auth }}"
     description: Demo Project
     domain: default
     region_name: "{{ region_name }}"
     state: present
     ca_cert: "{{ openstack_cacert }}"
  run_once: true
  when: region_name == region_main_site

- name: Create user demo
  os_user:
     name: demo
     auth: "{{ openstack_auth }}"
     password: "{{ demo_pass }}"
     domain: default
     region_name: "{{ region_name }}"
     ca_cert: "{{ openstack_cacert }}"
     state: present
  run_once: true
  when: region_name == region_main_site

- name: Create role user for Keystone
  os_keystone_role:
     state: present
     auth: "{{ openstack_auth }}"
     region_name: "{{ region_name }}"
     name: user
     ca_cert: "{{ openstack_cacert }}"
  run_once: true
  when: region_name == region_main_site

- name: Apply role for demo user
  os_user_role:
     auth: "{{ openstack_auth }}"
     user: demo 
     role: user
     project: demo
     region_name: "{{ region_name }}"
     ca_cert: "{{ openstack_cacert }}"
  run_once: true
  when: region_name == region_main_site

- name: Create role Member for Keystone
  os_keystone_role:
     state: present
     auth: "{{ openstack_auth }}"
     name: _member_
     ca_cert: "{{ openstack_cacert }}"
     region_name: "{{ region_name }}"
  run_once: true
  when: region_name == region_main_site

- name: Create enpoint for other site
  os_keystone_endpoint:
     auth: "{{ openstack_auth }}"
     service: keystone
     endpoint_interface: "{{ item }}"
     url: "{{ keystone_url }}"
     region: "{{ region_name }}"
     region_name: "{{ region_main_site }}"
     ca_cert: "{{ openstack_cacert }}"
     state: present
  with_items:
    - public
    - admin
    - internal
  delegate_to: "{{ other_site_ip_list[0] }}"
  vars:
     ansible_port: "{{ ssh_port_other_site }}"
  run_once: true
  when: region_name != region_main_site
