---
- name: restart service httpd
  systemd:
    state: restarted
    enabled: true
    name: httpd
  throttle: 1

- name: sleep for 10s and continue with play
  wait_for:
    timeout: 10
  delegate_to: localhost


