---
- name: restart service httpd
  systemd:
    state: restarted
    enabled: true
    name: httpd

- name: sleep for 10s and continue with play
  wait_for:
    timeout: 10
  delegate_to: localhost

- name: Create script test system
  template:
    src: script-test.sh.j2
    dest: /root/script-test.sh
    mode: 0751

